/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import pt.talkdesk.call.Caller;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import static org.junit.Assert.assertTrue;

public class CallerTest {
    @Test public void checkDates() {
        try {
            Date date1 = new SimpleDateFormat("hh:mm:ss").parse("09:11:30");
            Caller call = new Caller(date1,date1,"+351914374373","+351215355312");
            assertTrue("Date problems with the caller from'", call.getCallFrom().equals("+351914374373"));
            assertTrue("Date problems with the caller to", call.getCallTo().equals("+351215355312"));
            assertTrue("Date format Problems", (call.getTimeFinish().getTime()-date1.getTime())==0);
        } catch (ParseException e) {
            e.printStackTrace();
        }

    }
}
