/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import pt.talkdesk.utils.FileProcessor;

import static org.junit.Assert.assertTrue;

public class FileProcessorTest {
    @Test public void checkFileCorrect() {
        FileProcessor fileProcessor = new FileProcessor("Test");
        assertTrue("someLibraryMethod should return 'true'", fileProcessor.getFile().getName().equals("Test"));
    }
}
